### ISSUE TITLE
On the page http://www.learndatalogtoday.org/chapter/0 the button "Run Query" doesn't do anything

### ISSUE THREAD

**Issue by ashnur** [jonase/learndatalogtoday#28]
In the console however this message appears:
Uncaught Invalid match arg: 
/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/i

I am using Chromium 48 on Linux, although this shouldn't matter.

**Comment by SevereOverfl0w** [comment]
:+1: Also seeing this

**Comment by brianmingus** [comment]
@jonase your site is broken

**Comment by bburdette** [comment]
git cloned the project and it has the same problem running locally on my machine.  same error as ashnur.

**Comment by jonase** [comment]
Any help with this would be much appreciated. Updating cljs & cljsbuild deps might help. Updating codemirror to a later version might also help.

**Comment by ashnur** [comment]
@jonase actually, I think the only problem is that the feedback is almost impossible to notice, especially if someone has problems with the green/red colors.

**Comment by brianmingus** [comment]
@ashnur I'm not sure what you are referring to but for me the page is completely broken.

**Comment by ashnur** [comment]
@brianmingus I am "referring to" what I wrote in the issue title and body.

Also, "completely broken" sounds very serious, but sadly it can mean anything. It can mean that it doesn't load, loads only partially, loads fully but it's rendered wrongly, it's rendered good but then something happens and all disappears, it's rendered good but not the correct content, or maybe just the button doesn't do anything? Or maybe, as in my case, I didn't notice that in the case of correct answers, the number turns green. Which I missed completely for two days.

**Comment by bburdette** [comment]
So I was expecting to see results from the database, but maybe the only thing you get is that the number turns green?

**Comment by brianmingus** [comment]
@jonase it will be hard for us to fix the app if it is broken because we don't know the expected behavior. I think we were all definitely expecting more feedback than for a tab icon to turn green for sure.. for instance I expected to see real database output, and perhaps stack traces.

**Comment by jonase** [comment]
previously you would see the result set from the database in a table below the query and a note if the result is correct or not. Something has probably changed in either modern browsers or on Heroku to break the app since I haven't done a redeploy for a few years.

**Comment by kirillsalykin** [comment]
Also noticed the issue.
If it will help - ajax works properly, if you open network tab and inspect response - fetched data is there.

**Comment by fasiha** [comment]
In case it helps anyone, I wrote a tentative [port to DataScript](https://gist.github.com/fasiha/2ab2c1cb203c26a2b63532831f1b6021) that should run in-browser to in JVM, for REPL-based interactivity. That way I can follow along with Learn Datalog Today.

**Comment by mdgart** [comment]
@jonase  Looks like it's a bug in the clojurescript version that you are using, you should try to upgrade to a newer version. Look at this: https://github.com/lazerwalker/clojurescript-koans/issues/13

**Comment by onetom** [comment]
Thanks @fasiha for your port.
I've packaged it up as a boot project here: https://github.com/addplus/learn-datalog

**Comment by jonase** [comment]
This is now finally resolved
